obj-$(CONFIG_LLFREE) += llfree-core.o
ccflags-y += -I$(srctree)/mm/llfree/private -I$(srctree)/mm/llfree/llc/src
llfree-core-y := llfree.o llc/src/llfree.o llc/src/bitfield.o llc/src/child.o llc/src/local.o llc/src/lower.o llc/src/tree.o
