#!/usr/bin/env python3
"""Run the AE figures in order, sharing newly measured all-local baselines."""
import argparse
import datetime
import json
from pathlib import Path
import shlex
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]


def commands(args):
    mode = '--plan' if args.plan else '--parse-only' if args.parse_only else '--run'
    common = ['--inventory', str(args.inventory.resolve()), '--repeats', str(args.repeats), mode]
    output = args.results.resolve()
    result = []
    if args.figure in ('all', 'fig78'):
        argv = [sys.executable, str(ROOT / 'ae/scripts/ae_fig78.py'),
                *common, '--results', str(output / 'fig78')]
        if args.apps:
            argv += ['--apps', *args.apps]
        result.append(argv)
    if args.figure in ('all', 'fig9'):
        argv = [sys.executable, str(ROOT / 'ae/scripts/ae_fig9.py'),
                *common, '--results', str(output / 'fig9')]
        if args.figure == 'all' or (output / 'fig78/all-local.json').is_file():
            argv += ['--all-local', str(output / 'fig78/all-local.json')]
        if args.mixes:
            argv += ['--mixes', *args.mixes]
        result.append(argv)
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('figure', choices=['all', 'fig78', 'fig9'])
    parser.add_argument('--inventory', type=Path, default=ROOT / 'ae/config/host.json',
                        help='Site configuration generated by scripts/configure-site.py')
    parser.add_argument('--results', type=Path,
                        help='Output root; fig78/ and fig9/ are created beneath it')
    parser.add_argument('--apps', nargs='+', help='Optional Figure 7/8 application subset')
    parser.add_argument('--mixes', nargs='+', choices=['mix1', 'mix2', 'mix3', 'mix4'])
    parser.add_argument('--repeats', type=int, choices=(1, 2, 3), default=3)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--plan', action='store_true', help='Show the experiment plan without starting VMs')
    modes.add_argument('--run', action='store_true', help='Attempt three repetitions and draw successful measurements (default)')
    modes.add_argument('--parse-only', action='store_true', help='Reparse and redraw existing complete results')
    args = parser.parse_args(argv)
    if args.figure != 'fig9' and args.repeats != 3:
        parser.error('--repeats is only configurable for Figure 9')
    if args.parse_only and args.results is None:
        parser.error('--parse-only requires --results pointing to existing measurements')
    if args.figure == 'fig9' and args.apps:
        parser.error('--apps is only supported for Figure 7/8')
    if args.figure == 'fig78' and args.mixes:
        parser.error('--mixes is only supported for Figure 9')
    if args.figure == 'all' and args.apps:
        parser.error('Use fig78.sh for an application subset; run-all needs all isolated baselines')
    if args.results is None:
        tag = 'plan' if args.plan else datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
        args.results = ROOT / 'ae/results' / tag
    if args.figure == 'all' and not (args.plan or args.parse_only):
        # Catch an impossible Fig9 placement before hours of isolated runs.
        # Resource planning needs VM sizes/threads, not the future denominator.
        import ae_fig9
        high = json.loads((ROOT / 'ae/config/fig9-highs.json').read_text())
        for case, app in high['applications'].items():
            app['application'] = case
        ae_fig9.resource_plans(high, json.loads(args.inventory.read_text()),
                               args.mixes or list(ae_fig9.data.MIXES), require_feasible=True)
    failures = []
    for command in commands(args):
        print('+ ' + shlex.join(command), flush=True)
        try:
            subprocess.run(command, cwd=ROOT, check=True)
        except subprocess.CalledProcessError as error:
            if error.returncode in (130, 143, -2, -15):
                raise
            failures.append(error)
            print('Stage failed; continuing to the next stage: ' + str(error), file=sys.stderr)
    if not args.plan:
        print('Results: ' + str(args.results.resolve()), flush=True)
    if failures:
        raise failures[0]


if __name__ == '__main__':
    try:
        main()
    except subprocess.CalledProcessError as error:
        raise SystemExit(error.returncode)
    except (ValueError, OSError) as error:
        print('evaluate: ' + str(error), file=sys.stderr)
        raise SystemExit(1)
