#!/usr/bin/env python3
"""Run the AE figures in order, sharing newly measured all-local baselines."""
import argparse
import datetime
from pathlib import Path
import shlex
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]


def commands(args):
    mode = '--plan' if args.plan else '--parse-only' if args.parse_only else '--run'
    common = ['--inventory', str(args.inventory.resolve()), '--repeats', '3', mode]
    output = args.results.resolve()
    result = []
    if args.figure in ('all', 'fig78'):
        argv = [sys.executable, str(ROOT / 'ae/scripts/ae_fig78.py'),
                *common, '--results', str(output / 'fig78')]
        if args.apps:
            argv += ['--apps', *args.apps]
        result.append(argv)
    if args.figure in ('all', 'fig9'):
        argv = [sys.executable, str(ROOT / 'ae/scripts/ae_fig9.py'),
                *common, '--results', str(output / 'fig9')]
        if args.figure == 'all' or (output / 'fig78/all-local.json').is_file():
            argv += ['--all-local', str(output / 'fig78/all-local.json')]
        if args.mixes:
            argv += ['--mixes', *args.mixes]
        result.append(argv)
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('figure', choices=['all', 'fig78', 'fig9'])
    parser.add_argument('--inventory', type=Path, default=ROOT / 'ae/config/host.json',
                        help='Site configuration generated by scripts/configure-site.py')
    parser.add_argument('--results', type=Path,
                        help='Output root; fig78/ and fig9/ are created beneath it')
    parser.add_argument('--apps', nargs='+', help='Optional Figure 7/8 application subset')
    parser.add_argument('--mixes', nargs='+', choices=['mix1', 'mix2', 'mix3', 'mix4'])
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--plan', action='store_true', help='Show the experiment plan without starting VMs')
    modes.add_argument('--run', action='store_true', help='Run three repetitions and draw figures (default)')
    modes.add_argument('--parse-only', action='store_true', help='Reparse and redraw existing complete results')
    args = parser.parse_args(argv)
    if args.parse_only and args.results is None:
        parser.error('--parse-only requires --results pointing to existing measurements')
    if args.figure == 'fig9' and args.apps:
        parser.error('--apps is only supported for Figure 7/8')
    if args.figure == 'fig78' and args.mixes:
        parser.error('--mixes is only supported for Figure 9')
    if args.figure == 'all' and args.apps:
        parser.error('Use fig78.sh for an application subset; run-all needs all isolated baselines')
    if args.results is None:
        tag = 'plan' if args.plan else datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
        args.results = ROOT / 'ae/results' / tag
    for command in commands(args):
        print('+ ' + shlex.join(command), flush=True)
        subprocess.run(command, cwd=ROOT, check=True)
    if not args.plan:
        print('Results: ' + str(args.results.resolve()), flush=True)


if __name__ == '__main__':
    try:
        main()
    except subprocess.CalledProcessError as error:
        raise SystemExit(error.returncode)
